---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - dell.kubecon.dell.com
  resources:
  - servers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - dell.kubecon.dell.com
  resources:
  - servers/finalizers
  verbs:
  - update
- apiGroups:
  - dell.kubecon.dell.com
  resources:
  - servers/status
  verbs:
  - get
  - patch
  - update
